# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET Core'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: 'Database1/Database1.sqlproj'
    msbuildArguments: '/p OutDir=$(Build.ArtifactStagingDirectory)'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Azure-Devops02-CSharp'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudToken'
    organization: 'adamczepieldevops'
    scannerMode: 'MSBuild'
    projectKey: 'AdamCzepielDevops_Azure-Devops02-CSharp'
    projectName: 'Azure-Devops02-CSharp'
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: '**/*.csproj'
  
- task: DotNetCoreCLI@2
  displayName: 'Test .NET Core'
  inputs:
    command: 'test'
    projects: '**/*Test*/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish .NET Core'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

